spring:
  application:
    name: cloud-native-spring
endpoints:
  sensitive: false
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
management:
  security:
    enabled: false
  info:
      git:
        mode: full
  cloudfoundry:
    enabled: true
    skip-ssl-validation: false
security:
  basic:
    enabled: false